//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTE
    {
        public int CarteId { get; set; }
        public Nullable<int> AutorId { get; set; }
        public string Titlu { get; set; }
        public Nullable<int> GenId { get; set; }
    
        public virtual AUTOR AUTOR { get; set; }
        public virtual GEN GEN { get; set; }
    }
}
