//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW
    {
        public int ReviewId { get; set; }
        public Nullable<int> ImprumutId { get; set; }
        public string Text { get; set; }
    
        public virtual IMPRUMUT IMPRUMUT { get; set; }
    }
}
