//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carte
    {
        public int CarteId { get; set; }
        public string Titlu { get; set; }
        public int AutorId { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Gen GenId { get; set; }
    }
}
