//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imprumut
    {
        public int ImprumutId { get; set; }
        public System.DateTime DataImprumut { get; set; }
        public System.DateTime DataScadenta { get; set; }
        public System.DateTime DataRestituire { get; set; }
        public int CarteId { get; set; }
    
        public virtual Cititor CititorId { get; set; }
        public virtual Review Review { get; set; }
    }
}
